- name: varabiles in files
  hosts: localhost
  vars_files:
  - variable.yaml
  tasks:
  - name: based on files
    ansible.builtin.debug:
     msg: "i am learning {{course}}, trainer will be {{trainer}}, duration will be {{duration}}"