- name: data types
  hosts: localhost
  vars:
    NAME: Vamsi #key value
    Skills: #list type = -
    - Devops
    - Shell
    - Ansible
    - Linux
    Experience: #this a map type
     Devops: 7
     Aws: 4
    Trainer: true #boolean
  tasks:
  - name: print Name
    ansible.builtin.debug:
     msg: "name: {{NAME}}"

  - name: print Skills
    ansible.builtin.debug:
     msg: "Skills: {{Skills}}"

  - name: print Experience
    ansible.builtin.debug:
     msg: "Experience: {{Experience}}"

  - name: print Trainer
    ansible.builtin.debug:
     msg: "is he Trainer: {{Trainer}}"
    
    
    