- name: about conditions
  hosts: localhost
  tasks:
   - name: check the roboshop user exits
     ansible.builtin.command: id roboshop
     register: user
     ignore_errors: true

   -  name: print variable value
      ansible.builtin.debug:
       msg: "output: {{user}}"

   -  name: print exit status
      ansible.builtin.debug:
       msg: "status is: {{user.rc}}"